import type { Locale } from './locales';
// Each category describes a concrete discovery intent, rather than repeating the
// site's generic introduction across every landing page.
const entries: Record<string, Record<Locale, [string, string]>> = {
  agents: {'zh-CN':['Agent 协作','查找智能体编排、多 Agent 协作与任务执行插件。'], 'zh-TW':['Agent 協作','尋找智慧代理編排、多 Agent 協作與任務執行插件。'],en:['Agent collaboration','Explore agent orchestration, multi-agent collaboration and task execution plugins.'],ja:['Agent 連携','エージェントの構成、複数 Agent の連携、タスク実行のプラグインを探せます。'],ko:['Agent 협업','에이전트 구성, 다중 Agent 협업 및 작업 실행 플러그인을 찾아보세요.']},
  development: {'zh-CN':['开发工具','发现代码编辑、调试、版本管理与开发流程插件。'],'zh-TW':['開發工具','探索程式碼編輯、除錯、版本管理與開發流程插件。'],en:['Developer tools','Discover plugins for code editing, debugging, version control and development workflows.'],ja:['開発ツール','コード編集、デバッグ、バージョン管理、開発ワークフローのプラグインを探せます。'],ko:['개발 도구','코드 편집, 디버깅, 버전 관리 및 개발 워크플로 플러그인을 찾아보세요.']},
  finance: {'zh-CN':['金融数据','浏览金融信息、行情数据与研究辅助插件，核对数据来源和使用条件。'],'zh-TW':['金融資料','瀏覽金融資訊、行情資料與研究輔助插件，核對資料來源與使用條件。'],en:['Financial data','Browse financial information, market data and research plugins; check their sources and requirements.'],ja:['金融データ','金融情報、市場データ、調査支援のプラグインを探し、情報源と利用条件を確認できます。'],ko:['금융 데이터','금융 정보, 시장 데이터 및 조사 지원 플러그인을 살펴보고 출처와 이용 조건을 확인하세요.']},
  integrations: {'zh-CN':['服务集成','查找连接外部服务、API 与业务工具的插件，了解所需配置。'],'zh-TW':['服務整合','尋找連接外部服務、API 與業務工具的插件，了解必要設定。'],en:['Integrations','Find plugins that connect external services, APIs and business tools, with setup information.'],ja:['サービス連携','外部サービス、API、業務ツールを接続するプラグインと設定方法を探せます。'],ko:['서비스 연동','외부 서비스, API 및 업무 도구를 연결하는 플러그인과 설정 정보를 찾아보세요.']},
  interface: {'zh-CN':['界面扩展','发现面板、主题、终端与交互界面插件，调整 Harness 的使用体验。'],'zh-TW':['介面擴充','探索面板、主題、終端與互動介面插件，調整 Harness 的使用體驗。'],en:['Interface extensions','Explore panels, themes, terminals and interface plugins for your Harness workspace.'],ja:['インターフェース','Harness のパネル、テーマ、ターミナル、操作画面のプラグインを探せます。'],ko:['인터페이스 확장','Harness 작업 공간의 패널, 테마, 터미널 및 인터페이스 플러그인을 살펴보세요.']},
  memory: {'zh-CN':['记忆与知识库','查找会话记忆、知识库检索与上下文管理插件。'],'zh-TW':['記憶與知識庫','尋找對話記憶、知識庫檢索與上下文管理插件。'],en:['Memory and knowledge','Find plugins for conversation memory, knowledge retrieval and context management.'],ja:['メモリ・ナレッジ','会話の記憶、ナレッジ検索、コンテキスト管理のプラグインを探せます。'],ko:['메모리 및 지식','대화 기억, 지식 검색 및 컨텍스트 관리 플러그인을 찾아보세요.']},
  notifications: {'zh-CN':['消息通知','发现任务状态、消息推送与提醒插件，了解支持的通知渠道。'],'zh-TW':['訊息通知','探索任務狀態、訊息推送與提醒插件，了解支援的通知管道。'],en:['Notifications','Discover task updates, message delivery and reminder plugins and their supported channels.'],ja:['通知','タスクの進捗通知、メッセージ配信、リマインダーのプラグインを探せます。'],ko:['알림','작업 상태, 메시지 전송 및 리마인더 플러그인과 지원 채널을 찾아보세요.']},
  other: {'zh-CN':['其他扩展','探索其他用途的社区插件，查看说明文档以确认具体能力。'],'zh-TW':['其他擴充','探索其他用途的社群插件，查看說明文件以確認具體功能。'],en:['Other extensions','Explore community plugins for other tasks and check their documentation for specific capabilities.'],ja:['その他の拡張','その他の用途のコミュニティプラグインを探し、文書で機能を確認できます。'],ko:['기타 확장','다른 용도의 커뮤니티 플러그인을 살펴보고 문서에서 구체적인 기능을 확인하세요.']},
  productivity: {'zh-CN':['效率工具','查找任务管理、文档处理与日常流程自动化插件。'],'zh-TW':['效率工具','尋找任務管理、文件處理與日常流程自動化插件。'],en:['Productivity','Find task management, document processing and everyday workflow automation plugins.'],ja:['生産性ツール','タスク管理、文書処理、日常業務の自動化プラグインを探せます。'],ko:['생산성 도구','작업 관리, 문서 처리 및 일상 워크플로 자동화 플러그인을 찾아보세요.']},
  skills: {'zh-CN':['技能扩展','发现可复用技能、工具集合与任务能力扩展，了解安装和调用方法。'],'zh-TW':['技能擴充','探索可重用技能、工具集合與任務能力擴充，了解安裝及呼叫方法。'],en:['Skills','Discover reusable skills, tool collections and task capabilities with installation and usage instructions.'],ja:['スキル','再利用できるスキル、ツール集、タスク機能の導入方法と使い方を探せます。'],ko:['스킬','재사용 가능한 스킬, 도구 모음 및 작업 기능의 설치와 사용 방법을 찾아보세요.']},
  vision: {'zh-CN':['视觉工具','查找图像理解、截图分析与视觉交互插件，比较输入要求与使用方式。'],'zh-TW':['視覺工具','尋找影像理解、截圖分析與視覺互動插件，比較輸入需求與使用方式。'],en:['Vision tools','Find image understanding, screenshot analysis and visual interaction plugins; compare inputs and usage.'],ja:['視覚ツール','画像理解、スクリーンショット分析、視覚操作プラグインの入力条件と使い方を比較できます。'],ko:['시각 도구','이미지 이해, 스크린샷 분석 및 시각 상호작용 플러그인의 입력 조건과 사용법을 비교하세요.']},
};
export function categoryCopy(id: string, locale: Locale) { const [label, description] = entries[id]?.[locale] || [id, entries.other[locale][1]]; return {label, description}; }
export function categoryLabels(locale: Locale) { return Object.fromEntries(Object.keys(entries).map(id => [id, categoryCopy(id, locale).label])); }
export function listingTitle(locale: Locale, category?: string, page = 1) {
  const label = category ? categoryCopy(category, locale).label : '';
  const base = ({'zh-CN':`${label ? label + ' · ' : ''}DeepSeek Harness 插件`, 'zh-TW':`${label ? label + ' · ' : ''}DeepSeek Harness 插件`,en:`${label ? label + ' · ' : ''}DeepSeek Harness plugins`,ja:`${label ? label + ' · ' : ''}DeepSeek Harness プラグイン`,ko:`${label ? label + ' · ' : ''}DeepSeek Harness 플러그인`})[locale];
  const suffix = ({'zh-CN':`第 ${page} 页`,'zh-TW':`第 ${page} 頁`,en:`Page ${page}`,ja:`${page} ページ`,ko:`${page} 페이지`})[locale];
  return base + (page > 1 ? ` — ${suffix}` : '');
}
